export const metaCampaigns = [
  {
    id: "c1",
    name: "Verano 2025 — Conversiones",
    status: "active",
    budget: 1500,
    spent: 1023.4,
    impressions: 184200,
    reach: 102300,
    clicks: 3841,
    ctr: 2.09,
    cpc: 0.27,
    conversions: 284,
    cpa: 3.60,
    roas: 4.2,
    revenue: 4298.28,
    platform: "Instagram",
    objective: "Conversiones",
    startDate: "2025-06-01",
    endDate: "2025-06-30",
    trend: "+18%",
    trendUp: true,
  },
  {
    id: "c2",
    name: "Retargeting Q2",
    status: "active",
    budget: 800,
    spent: 612.8,
    impressions: 98700,
    reach: 47200,
    clicks: 2190,
    ctr: 2.22,
    cpc: 0.28,
    conversions: 189,
    cpa: 3.24,
    roas: 5.8,
    revenue: 3554.24,
    platform: "Facebook",
    objective: "Retargeting",
    startDate: "2025-05-15",
    endDate: "2025-07-15",
    trend: "+32%",
    trendUp: true,
  },
  {
    id: "c3",
    name: "Brand Awareness Mayo",
    status: "paused",
    budget: 500,
    spent: 500,
    impressions: 412000,
    reach: 298000,
    clicks: 1840,
    ctr: 0.45,
    cpc: 0.27,
    conversions: 42,
    cpa: 11.90,
    roas: 1.9,
    revenue: 950,
    platform: "Instagram",
    objective: "Alcance",
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    trend: "-5%",
    trendUp: false,
  },
  {
    id: "c4",
    name: "Lead Gen — Webinar",
    status: "active",
    budget: 1200,
    spent: 889.2,
    impressions: 76300,
    reach: 52100,
    clicks: 4102,
    ctr: 5.38,
    cpc: 0.22,
    conversions: 412,
    cpa: 2.16,
    roas: 6.1,
    revenue: 5423.12,
    platform: "Facebook",
    objective: "Generación de Leads",
    startDate: "2025-05-10",
    endDate: "2025-06-10",
    trend: "+47%",
    trendUp: true,
  },
  {
    id: "c5",
    name: "Catálogo — Productos Nuevos",
    status: "active",
    budget: 2000,
    spent: 1780.5,
    impressions: 229000,
    reach: 134000,
    clicks: 6890,
    ctr: 3.01,
    cpc: 0.26,
    conversions: 523,
    cpa: 3.40,
    roas: 4.9,
    revenue: 8724.45,
    platform: "Instagram + Facebook",
    objective: "Ventas de Catálogo",
    startDate: "2025-04-20",
    endDate: "2025-06-20",
    trend: "+21%",
    trendUp: true,
  },
];

export const salesData = [
  { month: "Ene", revenue: 12400, orders: 148, aov: 83.8 },
  { month: "Feb", revenue: 15200, orders: 172, aov: 88.4 },
  { month: "Mar", revenue: 18900, orders: 209, aov: 90.4 },
  { month: "Abr", revenue: 16700, orders: 188, aov: 88.8 },
  { month: "May", revenue: 22950, orders: 247, aov: 92.9 },
  { month: "Jun", revenue: 26400, orders: 281, aov: 93.9 },
];

export const weeklyData = [
  { day: "Lun", spend: 420, revenue: 1820, leads: 48 },
  { day: "Mar", spend: 380, revenue: 1640, leads: 42 },
  { day: "Mié", spend: 510, revenue: 2340, leads: 61 },
  { day: "Jue", spend: 490, revenue: 2180, leads: 57 },
  { day: "Vie", spend: 620, revenue: 2890, leads: 74 },
  { day: "Sáb", spend: 540, revenue: 2510, leads: 65 },
  { day: "Dom", spend: 310, revenue: 1420, leads: 38 },
];

export const funnelData = [
  { stage: "Impresiones", value: 1000000, pct: 100 },
  { stage: "Alcance", value: 633000, pct: 63.3 },
  { stage: "Clics", value: 18863, pct: 1.9 },
  { stage: "Visitas Landing", value: 14147, pct: 1.4 },
  { stage: "Add to Cart", value: 2829, pct: 0.28 },
  { stage: "Compras", value: 1450, pct: 0.15 },
];

export const researchItems = [
  {
    id: "r1",
    title: "Análisis Competitivo Q2 2025",
    category: "Competencia",
    date: "2025-05-10",
    summary: "Análisis detallado de los competidores principales en Meta Ads. Identificamos que los competidores A y B están invirtiendo en video corto con CPM promedio de $8.20, mientras que nosotros operamos a $6.40.",
    tags: ["meta", "competencia", "video"],
    priority: "alta",
    author: "Diego S.",
  },
  {
    id: "r2",
    title: "Tendencias de Audiencia — 18-34 años",
    category: "Audiencia",
    date: "2025-05-08",
    summary: "El segmento 18-24 muestra CTR 38% más alto en Instagram Stories vs Feed. Los intereses más rentables: fitness, tecnología y moda sustentable. LTV promedio del segmento: $340.",
    tags: ["audiencia", "instagram", "ctr"],
    priority: "alta",
    author: "Diego S.",
  },
  {
    id: "r3",
    title: "Mejores Horas de Publicación — Mayo 2025",
    category: "Optimización",
    date: "2025-05-05",
    summary: "Análisis de 90 días de datos: las horas pico son 7-9am y 7-9pm hora CDMX. Los miércoles y viernes generan 24% más conversiones. CPM más bajo los domingos por la mañana.",
    tags: ["scheduling", "optimización", "cpm"],
    priority: "media",
    author: "Diego S.",
  },
  {
    id: "r4",
    title: "Informe de Creativos — Video vs Imagen",
    category: "Creativos",
    date: "2025-04-28",
    summary: "Video corto (15s) supera a imágenes estáticas en 2.8x en CTR. Los Reels con subtítulos tienen 40% más retención. Hook en primeros 3 segundos es el factor #1 de éxito.",
    tags: ["creative", "video", "roas"],
    priority: "alta",
    author: "Diego S.",
  },
  {
    id: "r5",
    title: "Análisis de Palabras Clave — Google Trends",
    category: "SEO/SEM",
    date: "2025-04-20",
    summary: "Las búsquedas relacionadas aumentaron 45% YoY. Top keywords: [marca] + \"precio\" y [marca] + \"opiniones\". Oportunidad en long-tail de bajo CPC.",
    tags: ["seo", "keywords", "tendencias"],
    priority: "media",
    author: "Diego S.",
  },
  {
    id: "r6",
    title: "Benchmark de Industria — eCommerce México",
    category: "Industria",
    date: "2025-04-15",
    summary: "ROAS promedio industria: 3.2x. Nuestro ROAS: 4.8x (50% sobre benchmark). CPA industria: $5.80, nuestro CPA: $3.40. Estamos en top 20% del sector.",
    tags: ["benchmark", "ecommerce", "roas"],
    priority: "baja",
    author: "Diego S.",
  },
];

export const calendarEvents = [
  { id: "e1", title: "Launch — Verano 2025", date: "2025-06-01", type: "launch", color: "#22c55e" },
  { id: "e2", title: "Review Retargeting Q2", date: "2025-06-05", type: "review", color: "#3b82f6" },
  { id: "e3", title: "Entrega Creativos Julio", date: "2025-06-10", type: "deadline", color: "#f59e0b" },
  { id: "e4", title: "Webinar — Email Marketing", date: "2025-06-12", type: "event", color: "#a855f7" },
  { id: "e5", title: "Reporte Mensual Mayo", date: "2025-06-15", type: "report", color: "#3b82f6" },
  { id: "e6", title: "Pausa Campañas — Asueto", date: "2025-06-16", type: "pause", color: "#ef4444" },
  { id: "e7", title: "New Campaign Brief Q3", date: "2025-06-18", type: "planning", color: "#22c55e" },
  { id: "e8", title: "A/B Test Creativos", date: "2025-06-20", type: "test", color: "#f59e0b" },
  { id: "e9", title: "Budget Review Q2", date: "2025-06-25", type: "review", color: "#3b82f6" },
  { id: "e10", title: "Launch — Catálogo Julio", date: "2025-07-01", type: "launch", color: "#22c55e" },
];

export const notifications = [
  { id: "n1", type: "alert", message: "Campaña 'Retargeting Q2' alcanzó el 90% de presupuesto", time: "hace 5 min", read: false },
  { id: "n2", type: "success", message: "ROAS semanal supera benchmark: 5.8x vs 3.2x industria", time: "hace 2h", read: false },
  { id: "n3", type: "info", message: "Nuevo reporte de investigación disponible", time: "hace 4h", read: true },
  { id: "n4", type: "warning", message: "CTR de 'Brand Awareness' cayó 12% vs semana anterior", time: "hace 6h", read: true },
  { id: "n5", type: "success", message: "Campaña 'Lead Gen Webinar' logró 412 leads esta semana", time: "ayer", read: true },
];

export const kpis = {
  totalSpend: { value: 4806.9, change: "+12%", up: true, label: "Inversión Total (Mes)" },
  totalRevenue: { value: 22950, change: "+37%", up: true, label: "Ingresos (Mes)" },
  avgRoas: { value: 4.77, change: "+0.8", up: true, label: "ROAS Promedio" },
  totalLeads: { value: 1450, change: "+28%", up: true, label: "Conversiones" },
  avgCpa: { value: 3.31, change: "-8%", up: true, label: "CPA Promedio" },
  activeCampaigns: { value: 4, change: "0", up: true, label: "Campañas Activas" },
};
